### ISSUE TITLE
[zod-openapi] hono client type inference does not work with a chained route and middleware

### ISSUE THREAD

**Issue by kporten** [honojs/middleware#405] opened 2024-02-28 18:52 UTC
Currently `OpenAPIHono` types do not allow to chain `.use(...)` and `.openapi(...)` - even if everything works fine during runtime.

```ts
const app = new OpenAPIHono()
  .use(routeTest.getRoutingPath(), cors())
  .openapi(routeTest, (c) => c.json('test')); // Property 'openapi' does not exist on type 'Hono<Env, {}, "/">'.
```

And the hono client (RPC) does not work as well in this case:

```ts
const client = hc<typeof app>('http://localhost:8787/');
client. // Missing type inference
```

_(see example 1 in the Stackblitz setup)_

This kind of definition should be supported to use hono client (RPC) in larger applications with an OpenAPIHono setup:
https://hono.dev/guides/rpc#using-with-larger-applications

A workaround is type casting:

```ts
const app = (
  new OpenAPIHono()
    .use(routeTest.getRoutingPath(), cors()) as OpenAPIHono // casting from Hono to OpenAPIHono
  )
  .openapi(routeTest, (c) => c.json('test'));

const client = hc<typeof app>('http://localhost:8787/');
client.index.$get() // Type inference works now
```

_(see example 3 in the Stackblitz setup)_

**Setup to reproduce the error:**
https://stackblitz.com/edit/spvrub-hono-zod-openapi?file=src%2Fserver.ts&view=editor

**Comment by yusukebe** [comment] 2024-03-01 07:43
Hi @kporten 

> 1) chaining not supported by typescript

Hono Zod OpenAPI does not support changing.

> 2) separate rows work ...but hono client type inference does not work

Write like this:

```ts
const app = new OpenAPIHono();
app.use(routeTest.getRoutingPath(), cors());
const routes = app.openapi(routeTest, (c) => c.json('test'));
const client = hc<typeof routes>('http://localhost:8787/');
```

> 3) works, but casting is needed

Hono Zod OpenAPI does not support that syntax.

**Comment by yusukebe** [comment] 2024-03-01 07:43
Closing because this is not a bug.

**Closed by yusukebe** 2024-03-01 07:43 UTC
