### ISSUE TITLE
@hono/firebase-auth Error: Error fetching public keys for Google certs

### ISSUE THREAD

**Issue by arekgotfryd** [honojs/middleware#439] opened 2024-03-30 22:07 UTC
Hello,

I'm trying to setup `@hono/firebase-auth` but I'm getting
```
Object {
  message: failed to verify the requested firebase token,
  err: Error: Error fetching public keys for Google certs: TypeError: this.cfKVNamespace.get is not a func…
}
Error: failed to verify the requested firebase token: Error: Error fetching public keys for Google certs: TypeError: this.cfKVNamespace.get is not a function
```

Here is my package.json
```
{
  "name": "hono-minimal",
  "private": true,
  "version": "0.0.1",
  "main": "src/index.ts",
  "scripts": {
    "test": "jest --verbose --coverage",
    "dev": "wrangler dev src/index.ts",
    "deploy": "wrangler publish src/index.ts"
  },
  "license": "MIT",
  "dependencies": {
    "@hono/firebase-auth": "^1.4.0",
    "@turf/area": "^6.5.0",
    "@turf/bbox-polygon": "^6.5.0",
    "@turf/boolean-point-in-polygon": "^6.5.0",
    "@turf/centroid": "^6.5.0",
    "@turf/triangle-grid": "^6.5.0",
    "@turf/turf": "^6.5.0",
    "hono": "^3.12.12",
    "wicket": "^1.3.8"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20240222.0",
    "@types/jest": "^29.2.3",
    "esbuild": "^0.15.15",
    "esbuild-jest": "^0.5.0",
    "jest": "^29.3.1",
    "jest-environment-miniflare": "^2.11.0",
    "wrangler": "^2.4.4"
  }
}
```

**Comment by Code-Hex** [comment] 2024-03-31 02:22
@arekgotfryd hi👋
Could you give us a minimum reproduction code (or repository)? Thanks.

**Comment by arekgotfryd** [comment] 2024-03-31 09:13
Here is minimal repro
https://github.com/arekgotfryd/minimal-repro
in order to set it up locally on your machine you need to provide
some firebase and cloudflare related variables. All of them start with "YOUR" in order to find them easily.

**Comment by Code-Hex** [comment] 2024-03-31 13:57
@arekgotfryd Thanks for providing me the repository!

I have confirmed that the following modifications will work. Please try it.

```diff
diff --git a/wrangler.toml b/wrangler.toml
index 47641fb..70874f4 100644
--- a/wrangler.toml
+++ b/wrangler.toml
@@ -6,11 +6,10 @@ compatibility_date = "2022-11-22"
 logpush = true

 [vars]
-PUBLIC_JWK_CACHE_KV = "YOUR_PUBLIC_JWK_CACHE_KV"
 PUBLIC_JWK_CACHE_KEY = "YOUR_PUBLIC_JWK_CACHE_KEY"

 [[kv_namespaces]]
-binding = "YOUR_CLOUDFLARE_BINDING"
+binding = "PUBLIC_JWK_CACHE_KV"
 id = "YOUR_CLOUDFLARE_BINDING_ID"
 preview_id = "YOUR_CLOUDFLARE_BINDING_PREVIEW_ID"
```

**Comment by arekgotfryd** [comment] 2024-03-31 14:21
This is getting better as I get different error :)
```
Object {
  message: failed to verify the requested firebase token,
  err: TypeError: publicKeys is not iterable
    at PublicKeySignatureVerifier.verify (index.js:26383:29)
…
}
Error: failed to verify the requested firebase token: TypeError: publicKeys is not iterable
```
Which cert do you store in your cloudflare cache?
I'm using this one
https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com

**Comment by Code-Hex** [comment] 2024-04-01 02:07
@arekgotfryd The public key being used in this middleware is the one from the following URL:
https://github.com/Code-Hex/firebase-auth-cloudflare-workers/blob/e661f82a381a91a4a294758cff7f2f68dbedae97/src/token-verifier.ts#L367

How is the usage of the provided URL being handled? Since Cloudflare Workers cannot use X509 Certificate format public keys, the underlying library uses the JWK format.

**Comment by arekgotfryd** [comment] 2024-04-01 05:03
I switched to provided one and I'm getting
```
Object {
  message: failed to verify the requested firebase token,
  err: TypeError: publicKeys is not iterable
    at PublicKeySignatureVerifier.verify (index.js:26383:29)
…
}
```

**Comment by Code-Hex** [comment] 2024-04-01 05:20
@arekgotfryd Do you use https://github.com/arekgotfryd/minimal-repro ?
I can't reproduce it in my local 😢

**Comment by Code-Hex** [comment] 2024-04-01 05:27
Ah, I think you need to delete cache

**Comment by arekgotfryd** [comment] 2024-04-01 06:22
Thanks for help on this. I ended up implementing my own id token verification. Following below recommendations
https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library
This one can be closed.

**Comment by Code-Hex** [comment] 2024-04-01 08:07
@arekgotfryd Thanks for asking question to us!
Could you close this issue if possible? Thanks!

**Closed** 2024-04-01 08:11 UTC
