### ISSUE TITLE
[`@hono/zod-openapi`]: Defining a `defaultHook` higher in the hierarchy doesn't trigger.

### ISSUE THREAD

**Issue by Hugos68** [honojs/middleware#773] opened 2024-10-10 20:44 UTC
Minimal example:
```ts
// index.ts
import { OpenAPIHono } from "@hono/zod-openapi";
import users from './users.ts';

const app = new OpenAPIHono({ 
    defaultHook: console.log // Never triggers! Even though in `users.ts` -> `GET /users/{uuid}` validation fails
});

app.route('/users', users);

export default app;
```

```ts
// users.ts
import { OpenAPIHono, z } from "@hono/zod-openapi";

const app = new OpenAPIHono();

app.openapi(
	createRoute({
		method: "get",
		path: "/:id",
		request: {
			params: z.object({ id: z.string().uuid() }),
		},
		responses: { ... };
	}),
	async (c) => { ... },
);

export default app;
```

Then if I run and hit `/users/0` *nothing* console.logs.

Is this a bug or a feature? How do I go about globally handling validation errors?

**Comment by yusukebe** [comment] 2024-10-11 00:03
Hi @Hugos68 

It's not a bug. The `defaulHook` in the parent app in `index.ts` does not affect the child app in `users.ts`. You should add `defaultHook` to each child app.

**Comment by Hugos68** [comment] 2024-10-11 10:23
> It's not a bug. The defaulHook in the parent app in index.ts does not affect the child app in users.ts. You should add defaultHook to each child app.

That's a bit annoying, I have around 50 endpoints, do I really need to define the same handler 50 times?

**Comment by yusukebe** [comment] 2024-10-12 06:43
> That's a bit annoying, I have around 50 endpoints, do I really need to define the same handler 50 times?

Yes. There may be a good solution, but I don't know now.

Closing this issue.

**Closed by yusukebe** 2024-10-12 06:43 UTC
