### ISSUE TITLE
(zod-openapi): adding error responses in createRoute disables response type check

### ISSUE THREAD

**Issue by tmokmss** [honojs/middleware#872] opened 2024-12-06 14:54 UTC
With the below code with typo:
```ts
  const app = new OpenAPIHono();
  const route = createRoute({
    method: 'get',
    path: '/',
    request: {},
    responses: {
      200: {
        content: {
          'application/json': {
            schema: z.object({
              id: z.string(),
            }),
          },
        },
        description: 'foo',
      },
    },
  });

  app.openapi(route, async (c) => {
    return c.json({ id1: '1' }, 200);
  });
```

it raises a type error as 

> Property 'id' is missing in type '{ id1: string; }' but required in type '{ id: string; }'.

which is expected.

However, when I add an error response code like the blow:

```ts
  const app = new OpenAPIHono();
  const route = createRoute({
    method: 'get',
    path: '/',
    request: {},
    responses: {
      200: {
        content: {
          'application/json': {
            schema: z.object({
              id: z.string(),
            }),
          },
        },
        description: 'foo',
      },
      // ADD THIS
      400: {
        description: 'bad request',
      },
    },
  });

  app.openapi(route, async (c) => {
    return c.json({ id1: '1' }, 200);
  });
```

no error is reported from tsc. Is it expected? What should I do to force type check? Thanks.

**Comment by askorupskyy** [comment] 2024-12-13 00:41
I do experience this as well. Any response expects a content to be returned for the type to be valid.

In your case, you might want to do something like below to make it work properly.

```
400: {
      description: 'test',
      content: { 'application/json': { schema: z.null() } },
},
```

**Comment by tmokmss** [comment] 2024-12-21 14:10
@askorupskyy Thanks, it worked! I struggled with making `c.notFound()` work with your solution, but I finally abondoned it and returning json 404 directly.

```ts
  const route = createRoute({
    method: 'get',
    path: '/',
    request: {},
    responses: {
      200: {
        content: {
          'application/json': {
            schema: z.object({
              id: z.string(),
            }),
          },
        },
        description: 'foo',
      },
      404: {
        description: 'not found',
        content: { 'application/json': { schema: z.null() } },
      },
    },
  });

  app.openapi(route, async (c) => {
    if (somecondition) {
      return c.json(null, 404);
    }
    return c.json({ id1: '1' }, 200);
  });
```

**Comment by yusukebe** [comment] 2024-12-31 10:55
@askorupskyy Thank you!

@tmokmss Can you close this issue?

**Comment by tmokmss** [comment] 2024-12-31 10:59
i'm not sure if it's a bug or not, nor if it's an optimal solution. so I'll leave it to you. thanks!

**Comment by yusukebe** [comment] 2024-12-31 11:04
@tmokmss 

Thanks. It's not a bug, and it's OK if you solve it that way. I'll be closing.

**Closed by yusukebe** 2024-12-31 11:04 UTC
