### ISSUE TITLE
[zod-validator] Deno infers Context's Input to BlankInput

### ISSUE THREAD

**Issue by bakasmarius** [honojs/middleware#803] opened 2024-11-03 12:23 UTC
`Context` generics (specifically, `Input`) are inferred differently in `Deno` and `Node` for the same code.

Deno: v1.46.3; v2.0.3; v2.0.4
Node: v20.18.0
Hono: v4.6.8
@hono/zod-validator: v0.4.1
zod: v3.23.8

Node code:
```
import { Hono } from 'hono'
import { z } from 'zod'

import { zValidator } from '@hono/zod-validator'

const app = new Hono().put(
  '/posts',
  zValidator('json', z.object({ id: z.number() })),
  (c) => {
    const json = c.req.valid('json')
    return c.json({ status: 'ok' })
  }
)
```
TypeScript infers `c` to:
```
(parameter) c: Context<{}, "/posts", {
    in: {
        json: {
            id: number;
        };
    };
    out: {
        json: {
            id: number;
        };
    };
}>
```

Deno code:
```
import { z } from 'npm:zod@3.23.8'

import { zValidator } from 'npm:@hono/zod-validator@0.4.1'
import { Hono } from 'npm:hono@4.6.8'

const app = new Hono().put(
  '/posts',
  zValidator('json', z.object({ id: z.number() })),
  (c) => {
    const json = c.req.valid('json')
    return c.json({ status: 'ok' })
  },
)
```

TypeScript infers `c` to:
```
(parameter) c: Context<{}, "/posts", BlankInput>
```
Which results in `c.req.valid('json')` error: `Argument of type 'string' is not assignable to parameter of type 'never'.deno-ts(2345)`

**Comment by yusukebe** [comment] 2024-11-04 01:48
Hi @bakasmarius 

It is not reproduced. Works well in my environment:

![CleanShot 2024-11-04 at 10 47 15@2x](https://github.com/user-attachments/assets/8add5ff1-fd65-432f-ae52-213135785cd9)

Please clear the cache and try it again:

```
deno cache --reload main.ts
```

**Comment by Amatewasu** [comment] 2024-11-13 18:40
I've found something interesting.

Hono 4.6.8:
```ts
import { z } from "npm:zod@3.23.8";

import { zValidator } from "npm:@hono/zod-validator@0.4.1";
import { Hono } from "npm:hono@4.6.8";

const app = new Hono().put(
  "/posts",
  zValidator("json", z.object({ id: z.number() })),
  (c) => {
    const json = c.req.valid("json");
    return c.json({ status: "ok" });
  }
);
```

Result: OK
![image](https://github.com/user-attachments/assets/da25e19d-b1a1-48b8-a1c7-9f4afc3882f2)
[Codesandbox Hono 4.6.8 OK](https://codesandbox.io/p/devbox/elegant-neumann-6txsm4?file=%2Findex.ts%3A12%2C4)

Hono 4.6.10:
```ts
import { z } from "npm:zod@3.23.8";

import { zValidator } from "npm:@hono/zod-validator@0.4.1";
import { Hono } from "npm:hono@4.6.10";

const app = new Hono().put(
  "/posts",
  zValidator("json", z.object({ id: z.number() })),
  (c) => {
    const json = c.req.valid("json");
    return c.json({ status: "ok" });
  }
);
```
Result: NOK
![image](https://github.com/user-attachments/assets/ee988815-0287-4897-a350-547959eaad0e)
[Codesandbox Hono 4.6.10 NOK](https://codesandbox.io/p/devbox/elegant-neumann-forked-9z5lr4?file=%2Findex.ts%3A1%2C1-14%2C1&workspaceId=c17e4aa3-a191-47dd-a1a8-14157a703391)

Do you have the same result?

**Comment by yusukebe** [comment] 2024-11-13 19:02
Hi @Amatewasu 

I can't reproduce it. Works well.

![CleanShot 2024-11-14 at 04 02 21@2x](https://github.com/user-attachments/assets/5b78bf22-1a42-4d26-a015-3485071494ba)

**Comment by yusukebe** [comment] 2024-11-13 19:03
Maybe we can close this issue.

**Comment by TeoAvignon** [comment] 2024-11-14 08:11
I have the same error on the sandbox too (I am using chrome Version 130.0.6723.117)

![image](https://github.com/user-attachments/assets/ddcae1e6-2c6e-49a8-996d-9c27bec97a8f)

**Comment by moreirathomas** [comment] 2024-11-14 08:20
Hello :)

I do reproduce the issue.

```ts
// main.ts
import { z } from "npm:zod@3.23.8";

import { zValidator } from "npm:@hono/zod-validator@0.4.1";
import { Hono } from "npm:hono@4.6.10";

const app = new Hono().put(
  "/posts",
  zValidator("json", z.object({ id: z.number() })), // No overload matches this call. (see below)
  (c) => {
    const json = c.req.valid("json"); // Argument of type 'string' is not assignable to parameter of type 'never'.deno-ts(2345)

    return c.json({ status: "ok" });
  }
);
```

The actual error I get even before the invalid inference of `c.req.valid("json")` is this (second argument to `.put()`, the zod validator):

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'MiddlewareHandler<Env, string, { in: { json: { id: number; }; }; out: { json: { id: number; }; }; }>' is not assignable to parameter of type 'H<BlankEnv, "/posts", BlankInput, HandlerResponse<any>>'.
      Type 'MiddlewareHandler<Env, string, { in: { json: { id: number; }; }; out: { json: { id: number; }; }; }>' is not assignable to type 'MiddlewareHandler<BlankEnv, "/posts", BlankInput>'.
        Types of parameters 'c' and 'c' are incompatible.
          Type 'Context<BlankEnv, "/posts", BlankInput>' is not assignable to type 'Context<Env, string, { in: { json: { id: number; }; }; out: { json: { id: number; }; }; }>'.
            Types of property 'env' are incompatible.
              Type 'unknown' is not assignable to type 'object | undefined'.deno-ts(2769)
types.d.ts(389, 5): The last overload is declared here.
``` 

I also did reload the deno cache (`deno cache --reload main.ts`).


Versions:
```
deno 2.0.6 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2
zod 3.23.8
@hono/zod-validator 0.4.1
hono 4.6.10
```

---

Note that this **does not** happen in hono version 4.6.8. I can reproduce from version 4.6.9 (same error).

I will try to look for a change between 4.6.8 and 4.6.9 that could have created this issue.

**Comment by yusukebe** [comment] 2024-11-14 08:38
Hmmm. I can't reproduce it. Is that error happen on VSCode? If so, please try to restart the language server.

![CleanShot 2024-11-14 at 17 33 38@2x](https://github.com/user-attachments/assets/5b1314b4-2ef8-4170-aade-4948cbaac2c2)

**Comment by moreirathomas** [comment] 2024-11-14 09:01
Ok found the issue! I can confirm it is not a Hono issue :)

Explanation:

When trying to test between version 4.6.8 and 4.6.10, I simply changed the bare import specifier in the ts file and ran `deno cache --reload main.ts`.

```diff
- import { Hono } from "npm:hono@4.6.8";
+ import { Hono } from "npm:hono@4.6.10";
```

In the background, this wrote to deno.lock:
```json
{
  "version": "4",
  "specifiers": {
    "npm:@hono/zod-validator@0.4.1": "0.4.1_hono@4.6.10_zod@3.23.8",
    "npm:hono@4.6.10": "4.6.10",
    "npm:hono@4.6.8": "4.6.8",
    "npm:zod@3.23.8": "3.23.8"
  },
  "npm": {
    "@hono/zod-validator@0.4.1_hono@4.6.10_zod@3.23.8": {
      "integrity": "sha512-I8LyfeJfvVmC5hPjZ2Iij7RjexlgSBT7QJudZ4JvNPLxn0JQ3sqclz2zydlwISAnw21D2n4LQ0nfZdoiv9fQQA==",
      "dependencies": [
        "hono@4.6.10",
        "zod"
      ]
    },
    "hono@4.6.10": {
      "integrity": "sha512-IXXNfRAZEahFnWBhUUlqKEGF9upeE6hZoRZszvNkyAz/CYp+iVbxm3viMvStlagRJohjlBRGOQ7f4jfcV0XMGg=="
    },
    "hono@4.6.8": {
      "integrity": "sha512-f+2Ec9JAzabT61pglDiLJcF/DjiSefZkjCn9bzm1cYLGkD5ExJ3Jnv93ax9h0bn7UPLHF81KktoyjdQfWI2n1Q=="
    },
    "zod@3.23.8": {
      "integrity": "sha512-XBx9AXhXktjUqnepgTiE5flcKIYWi/rme0Eaj+5Y0lftuGBq+jyRu/md4WnuxqgP1ubdpNCsYEYPxrzVHD8d6g=="
    }
  },
  "workspace": {
    "dependencies": [
      "jsr:@std/assert@1"
    ]
  }
}
```

You can see a 2 Hono specifiers: one per version. This messes up the type inference of `MiddlewareHandler` because TypeScript somehow tries to read the types declaration of both versions:

```ts
const validator: MiddlewareHandler<
  {
    Variables: { hello: "world" };
    Bindings: undefined;
  },
  string,
  {
    in: { json: { id: number } };
    out: { json: { id: number } };
  }
> = zValidator("json", z.object({ id: z.number() }));
```

This produces a type error when typing `validator: MiddlwareHandler<...` where we can see that it tries to merge types from `hono/4.6.8/dist/types/types` and `hono/4.6.10/dist/types/types`:

```
Type 'MiddlewareHandler<Env, string, { in: { json: { id: number; }; }; out: { json: { id: number; }; }; }>' is not assignable to type 'MiddlewareHandler<{ Variables: { hello: "world"; }; Bindings: undefined; }, string, { in: { json: { id: number; }; }; out: { json: { id: number; }; }; }>'.
  Types of parameters 'c' and 'c' are incompatible.
    Type 'Context<{ Variables: { hello: "world"; }; Bindings: undefined; }, string, { in: { json: { id: number; }; }; out: { json: { id: number; }; }; }>' is not assignable to type 'Context<Env, string, { in: { json: { id: number; }; }; out: { json: { id: number; }; }; }>'.
      The types of 'req.matchedRoutes' are incompatible between these types.
        Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").RouterRoute[]' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").RouterRoute[]'.
          Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").RouterRoute' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").RouterRoute'.
            Types of property 'handler' are incompatible.
              Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").H<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").BlankInput, any>' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").H<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").BlankInput, any>'.
                Type 'Handler<any, any, BlankInput, any>' is not assignable to type 'H<any, any, BlankInput, any>'.
                  Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").Handler<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").BlankInput, any>' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").Handler<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").BlankInput, any>'.
                    Types of parameters 'c' and 'c' are incompatible.
                      Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/context").Context<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").BlankInput>' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/context").Context<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").BlankInput>'.
                        The types of 'req.matchedRoutes' are incompatible between these types.
                          Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").RouterRoute[]' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").RouterRoute[]'.
                            Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").RouterRoute' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").RouterRoute'.
                              Types of property 'handler' are incompatible.
                                Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").H<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").BlankInput, any>' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").H<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").BlankInput, any>'.
                                  Type 'Handler<any, any, BlankInput, any>' is not assignable to type 'H<any, any, BlankInput, any>'.
                                    Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").Handler<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").BlankInput, any>' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").Handler<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").BlankInput, any>'.
                                      Types of parameters 'c' and 'c' are incompatible.
                                        Type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/context").Context<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.8/dist/types/types").BlankInput>' is not assignable to type 'import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/context").Context<any, any, import("file:///home/thomasmoreira/.cache/deno/npm/registry.npmjs.org/hono/4.6.10/dist/types/types").BlankInput>'.
                                          Types of property 'redirect' are incompatible.
                                            Type '<T extends RedirectStatusCode = 302>(location: string, status?: T | undefined) => Response & TypedResponse<undefined, T, "redirect">' is not assignable to type '<T extends RedirectStatusCode = 302>(location: string | URL, status?: T | undefined) => Response & TypedResponse<undefined, T, "redirect">'.
                                              Types of parameters 'location' and 'location' are incompatible.
                                                Type 'string | URL' is not assignable to type 'string'.
                                                  Type 'URL' is not assignable to type 'string'.
```

I simply fixed the issue by keeping only one dependency declared in `deno.lock`. Maybe this is a Deno/TypeScript issue?

Thanks for the help :)

**Comment by yusukebe** [comment] 2024-12-08 23:29
Hi. It's not a Hono-side issue. So, I'll close this now. Thanks.

**Closed by yusukebe** 2024-12-08 23:29 UTC

**Comment by shareef99** [comment] 2024-12-22 17:12
I also encounter this error, I was about to solve this by clearing the cache.

`deno cache --reload ./src/main.ts`

**Comment by emonadeo** [comment] 2025-01-24 16:13
Stumbled across this today but it didn't work despite making sure the same Hono version is used.

Turns out the same problem occurs when you install Hono from JSR (`jsr:@hono/hono`), because zod-validator pulls its hono version from npm. Unfortunately despite being the same semver version of Hono, JSR and NPM cannot be mixed here as it breaks type inference regardless.

Not a Hono issue, just an FYI.
